### ISSUE TITLE
favicons are genereted but not reachable

### ISSUE THREAD

**Issue by ghost** [ZuluPro/django-super-favicon#5]
I have followed the instruction given in the readme file:

- I have installed your app;
- listed in the installed apps;
- loaded the templatetag `{% load favicon %}` in my base.html before anything;
- added `{% get_favicons %}` in the `head` section;
- generated the favicons successfully via terminal.

Everything works fine: favicons are generated in the `static` folder, html is injected in the head section, but images are not reachable, django returns a 404 not found page when requested!

Is there something I am missing?

**Comment by ZuluPro** [comment]
@dcdeiv Favicon is supposed to work like `collectstatic`. So if you have `DEBUG=True`, Django will try to serve statics, but favicons aren't here.
